[
    [
        "hybvrshyrvtym.1",
        "shyrvtytorbox",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.pov/?mode=navigator.build_shortcut_folder_list&shortcut_folder=True&name=Connect+Services\",return)"
    ],
    [
        "hybvrshyrvtym.1",
        "shyrvtytorbox",
        "widgetTarget",
        "videos"
    ],
    [
        "hybvrshyrvtym.1",
        "shyrvtytorbox",
        "widgetAspect",
        "Square"
    ],
    [
        "hybvrshyrvtym.1",
        "shyrvtytorbox",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "hybvrshyrvtym.1",
        "shyrvtytorbox",
        "thumb",
        "special://home/addons/plugin.video.pov/resources/skins/Default/media/mk_torbox.png"
    ],
    [
        "thzvkh.1",
        "thzvkh",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.program.masterkodi.il.wizard/?mode=maintenance_folder\",return)"
    ],
    [
        "thzvkh.1",
        "thzvkh",
        "widgetTarget",
        "videos"
    ],
    [
        "thzvkh.1",
        "thzvkh",
        "widgetAspect",
        "Square"
    ],
    [
        "thzvkh.1",
        "thzvkh",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "thzvkh.1",
        "thzvkh",
        "thumb",
        "special://home/addons/plugin.program.masterkodi.il.wizard/resources/art/maint/arrows-rotate.png"
    ],
    [
        "srtym.1",
        "hmshkhtspyyh",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.pov/?name=Continue Watching&mode=build_movie_list&action=in_progress_movies&random_support=true&iconImage=player\",return)"
    ],
    [
        "srtym.1",
        "hmshkhtspyyh",
        "widgetTarget",
        "videos"
    ],
    [
        "srtym.1",
        "hmshkhtspyyh",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "srtym.1",
        "hmshkhtspyyh",
        "thumb",
        "special://home/addons/plugin.video.pov/resources/skins/Default/media/player.png"
    ],
    [
        "srtym.1",
        "hm-khshyv",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.themoviedb.helper/?info=trakt_trending&tmdb_type=movie&reload=%24INFO%5BWindow%28Home%29.Property%28TMDbHelper.Widgets.Reload%29%5D&widget=true\",return)"
    ],
    [
        "srtym.1",
        "hm-khshyv",
        "widgetTarget",
        "videos"
    ],
    [
        "srtym.1",
        "hm-khshyv",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "srtym.1",
        "hm-khshyv",
        "thumb",
        "special://home/addons/plugin.video.pov/resources/skins/Default/media/trending.png"
    ],
    [
        "srtym.1",
        "bkvlnv",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.themoviedb.helper/?info=now_playing&tmdb_type=movie&reload=%24INFO%5BWindow%28Home%29.Property%28TMDbHelper.Widgets.Reload%29%5D&widget=true\",return)"
    ],
    [
        "srtym.1",
        "bkvlnv",
        "widgetTarget",
        "videos"
    ],
    [
        "srtym.1",
        "bkvlnv",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "srtym.1",
        "bkvlnv",
        "thumb",
        "special://home/addons/plugin.video.pov/resources/skins/Default/media/intheatres.png"
    ],
    [
        "srtym.1",
        "shvbrykvpvt",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.themoviedb.helper/?info=revenue_movies&tmdb_type=movie&reload=%24INFO%5BWindow%28Home%29.Property%28TMDbHelper.Widgets.Reload%29%5D&widget=true\",return)"
    ],
    [
        "srtym.1",
        "shvbrykvpvt",
        "widgetTarget",
        "videos"
    ],
    [
        "srtym.1",
        "shvbrykvpvt",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "srtym.1",
        "shvbrykvpvt",
        "thumb",
        "special://home/addons/plugin.video.pov/resources/skins/Default/media/most_voted.png"
    ],
    [
        "srtym.1",
        "zvkhyavskr",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.themoviedb.helper/?info=top_rated&tmdb_type=movie&reload=%24INFO%5BWindow%28Home%29.Property%28TMDbHelper.Widgets.Reload%29%5D&widget=true\",return)"
    ],
    [
        "srtym.1",
        "zvkhyavskr",
        "widgetTarget",
        "videos"
    ],
    [
        "srtym.1",
        "zvkhyavskr",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "srtym.1",
        "zvkhyavskr",
        "thumb",
        "special://home/addons/plugin.video.pov/resources/skins/Default/media/oscar_winners.png"
    ],
    [
        "srtym.1",
        "zanrym",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.themoviedb.helper/?info=genres&tmdb_type=movie&reload=%24INFO%5BWindow%28Home%29.Property%28TMDbHelper.Widgets.Reload%29%5D&widget=true\",return)"
    ],
    [
        "srtym.1",
        "zanrym",
        "widgetTarget",
        "videos"
    ],
    [
        "srtym.1",
        "zanrym",
        "widgetAspect",
        "Square"
    ],
    [
        "srtym.1",
        "zanrym",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "srtym.1",
        "zanrym",
        "thumb",
        "special://home/addons/plugin.video.pov/resources/skins/Default/media/genres.png"
    ],
    [
        "sdrvt.1",
        "hmshkhtspyyh",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.pov/?name=In+Progress&mode=build_tvshow_list&action=in_progress_tvshows&iconImage=in_progress_tvshow\",return)"
    ],
    [
        "sdrvt.1",
        "hmshkhtspyyh",
        "widgetTarget",
        "videos"
    ],
    [
        "sdrvt.1",
        "hmshkhtspyyh",
        "widgetAspect",
        "Poster"
    ],
    [
        "sdrvt.1",
        "hmshkhtspyyh",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "sdrvt.1",
        "hmshkhtspyyh",
        "thumb",
        "special://home/addons/plugin.video.pov/resources/skins/Default/media/player.png"
    ],
    [
        "sdrvt.1",
        "hm-khshyv",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.themoviedb.helper/?info=trakt_trending&tmdb_type=tv&reload=%24INFO%5BWindow%28Home%29.Property%28TMDbHelper.Widgets.Reload%29%5D&widget=true\",return)"
    ],
    [
        "sdrvt.1",
        "hm-khshyv",
        "widgetTarget",
        "videos"
    ],
    [
        "sdrvt.1",
        "hm-khshyv",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "sdrvt.1",
        "hm-khshyv",
        "thumb",
        "special://home/addons/plugin.video.pov/resources/skins/Default/media/trending.png"
    ],
    [
        "sdrvt.1",
        "rshtvtstrymyng",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.themoviedb.helper/?info=dir_custom_node&filename=SELECTED%20NETWORKS.json&plugin_category=SELECTED%20NETWORKS&reload=%24INFO%5BWindow%28Home%29.Property%28TMDbHelper.Widgets.Reload%29%5D&widget=true\",return)"
    ],
    [
        "sdrvt.1",
        "rshtvtstrymyng",
        "widgetTarget",
        "videos"
    ],
    [
        "sdrvt.1",
        "rshtvtstrymyng",
        "widgetAspect",
        "Big Square"
    ],
    [
        "sdrvt.1",
        "rshtvtstrymyng",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "sdrvt.1",
        "rshtvtstrymyng",
        "thumb",
        "special://home/addons/plugin.video.pov/resources/skins/Default/media/folder.png"
    ],
    [
        "sdrvt.1",
        "shydvrbkhvrh",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.themoviedb.helper/?info=airing_today&tmdb_type=tv&reload=%24INFO%5BWindow%28Home%29.Property%28TMDbHelper.Widgets.Reload%29%5D&widget=true\",return)"
    ],
    [
        "sdrvt.1",
        "shydvrbkhvrh",
        "widgetTarget",
        "videos"
    ],
    [
        "sdrvt.1",
        "shydvrbkhvrh",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "sdrvt.1",
        "shydvrbkhvrh",
        "thumb",
        "special://home/addons/plugin.video.pov/resources/skins/Default/media/fresh.png"
    ],
    [
        "sdrvt.1",
        "bkrvb",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.themoviedb.helper/?info=upcoming&tmdb_type=tv&reload=%24INFO%5BWindow%28Home%29.Property%28TMDbHelper.Widgets.Reload%29%5D&widget=true\",return)"
    ],
    [
        "sdrvt.1",
        "bkrvb",
        "widgetTarget",
        "videos"
    ],
    [
        "sdrvt.1",
        "bkrvb",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "sdrvt.1",
        "bkrvb",
        "thumb",
        "special://home/addons/plugin.video.pov/resources/skins/Default/media/lists.png"
    ],
    [
        "sdrvt.1",
        "zanrym",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.themoviedb.helper/?info=genres&tmdb_type=tv&reload=%24INFO%5BWindow%28Home%29.Property%28TMDbHelper.Widgets.Reload%29%5D&widget=true\",return)"
    ],
    [
        "sdrvt.1",
        "zanrym",
        "widgetTarget",
        "videos"
    ],
    [
        "sdrvt.1",
        "zanrym",
        "widgetAspect",
        "Square"
    ],
    [
        "sdrvt.1",
        "zanrym",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "sdrvt.1",
        "zanrym",
        "thumb",
        "special://home/addons/plugin.video.pov/resources/skins/Default/media/genres.png"
    ],
    [
        "mainmenu",
        "srtym",
        "icon",
        "special://skin/extras/icons/director.png"
    ],
    [
        "mainmenu",
        "srtym",
        "thumb",
        "special://skin/extras/icons/director.png"
    ],
    [
        "mainmenu",
        "sdrvt",
        "icon",
        "special://skin/extras/icons/tv.png"
    ],
    [
        "mainmenu",
        "sdrvt",
        "thumb",
        "special://skin/extras/icons/tv.png"
    ],
    [
        "mainmenu",
        "137",
        "icon",
        "special://skin/extras/icons/search.png"
    ],
    [
        "mainmenu",
        "hybvrshyrvtym",
        "icon",
        "special://skin/extras/icons/configure.png"
    ],
    [
        "mainmenu",
        "hybvrshyrvtym",
        "thumb",
        "special://skin/extras/icons/configure.png"
    ],
    [
        "mainmenu",
        "thzvkh",
        "icon",
        "special://home/addons/plugin.program.masterkodi.il.wizard/resources/art/maint/arrows-rotate.png"
    ],
    [
        "mainmenu",
        "thzvkh",
        "thumb",
        "special://home/addons/plugin.program.masterkodi.il.wizard/resources/art/maint/arrows-rotate.png"
    ],
    [
        "mainmenu",
        "hhlptskyn",
        "icon",
        "DefaultAddonSkin.png"
    ],
    [
        "mainmenu",
        "hhlptskyn",
        "thumb",
        "special://skin/extras/icons/"
    ],
    [
        "mainmenu",
        "5",
        "icon",
        "special://skin/extras/icons/settings.png"
    ],
    [
        "mainmenu",
        "13012",
        "icon",
        "special://skin/extras/icons/power.png"
    ]
]