# -*- coding: utf-8 -*-
"""
MasterKodi IL Wizard - Backup / Restore

Design goals (rewritten 2.3.5):
  * Protect what users can't afford to lose on a reinstall: the Gemini API
    key (gearsai), debrid tokens + Trakt (Gears), Hebrew/wizard state, and
    favourites/sources/guisettings.
  * FILE-based capture (copy the addon_data settings.xml) instead of reading
    individual setting keys -- it grabs *every* setting at once and restores
    even when the add-on isn't loaded (e.g. right after a fresh install).
  * Two scopes: QUICK (settings + keys, small) and FULL (whole userdata minus
    volatile caches).
  * Each backup carries a manifest.json so Restore can show/validate it.
  * Location is configurable (config.backup_location) so backups can live on
    external storage and survive a full build reinstall.
"""
import os
import json
import shutil
import zipfile
import xbmc
import xbmcgui
from datetime import datetime

from resources.libs import config as C

ADDON_NAME = C.ADDON_NAME
SUCCESS, ERROR, WARN = C.COLOR_SUCCESS, C.COLOR_ERROR, C.COLOR_WARNING

# Dirs/files we never want inside a FULL backup (huge + regenerated by Kodi).
FULL_EXCLUDE_DIRS = {'Thumbnails', 'packages', 'temp', 'archive_cache', 'cache'}
FULL_EXCLUDE_PREFIX = ('Textures',)  # Database/Textures13.db etc.


def log(msg, level=xbmc.LOGINFO):
    xbmc.log(f'[{C.ADDON_ID}] Backup: {msg}', level)


def _kodi_version():
    try:
        return xbmc.getInfoLabel('System.BuildVersion').split(' ')[0]
    except Exception:
        return '?'


def _addon_settings_file(addon_id):
    return os.path.join(C.ADDON_DATA_PATH, addon_id, 'settings.xml')


class BackupManager:
    # What QUICK grabs: (label, absolute source path, arc path inside the zip)
    def _quick_items(self):
        items = [
            ('הגדרות Gears (דבריד/Trakt)', _addon_settings_file(C.GEARS_ADDON_ID),
             f'addon_data/{C.GEARS_ADDON_ID}/settings.xml'),
            ('מפתח Gemini + כתוביות AI', _addon_settings_file(C.GEARSAI_ADDON_ID),
             f'addon_data/{C.GEARSAI_ADDON_ID}/settings.xml'),
            # ALL optional skins' settings, not just AF3 (pre-multi-skin residue
            # backed up AF3 even when the user ran Zephyr/Nimbus)
            *[(f'הגדרות סקין ({sid})', _addon_settings_file(sid),
               f'addon_data/{sid}/settings.xml')
              for sid in ('skin.arctic.fuse.3', 'skin.nimbus',
                          'skin.arctic.zephyr.2.resurrection.mod', 'skin.estuary')],
            ('מצב האשף (גרסאות עברית)', _addon_settings_file(C.ADDON_ID),
             f'addon_data/{C.ADDON_ID}/settings.xml'),
            ('guisettings.xml', C.GUISETTINGS, 'guisettings.xml'),
            ('sources.xml', C.SOURCES, 'sources.xml'),
            ('favourites.xml', C.FAVOURITES, 'favourites.xml'),
        ]
        return [(lbl, src, arc) for (lbl, src, arc) in items if os.path.exists(src)]

    # ---- create ----
    def create(self, scope='quick', progress_cb=None):
        ts = datetime.now()
        name = f"MasterKodiIL_{scope}_{ts.strftime('%Y%m%d_%H%M%S')}"
        dest_dir = C.backup_location()
        zip_path = os.path.join(dest_dir, name + '.zip')
        included = []
        try:
            with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as z:
                if scope == 'full':
                    self._add_full_userdata(z, progress_cb, included)
                else:
                    items = self._quick_items()
                    total = max(len(items), 1)
                    for i, (lbl, src, arc) in enumerate(items):
                        if progress_cb:
                            progress_cb(f'מגבה: {lbl}', int(10 + 80 * i / total))
                        z.write(src, arc)
                        included.append(lbl)

                manifest = {
                    'created': ts.strftime('%Y-%m-%d %H:%M:%S'),
                    'scope': scope,
                    'wizard_version': C.ADDON_VERSION,
                    'kodi_version': _kodi_version(),
                    'build_name': C.ADDON.getSetting('buildname') or '',
                    'build_version': C.ADDON.getSetting('buildversion') or '',
                    'items': included,
                }
                z.writestr('manifest.json', json.dumps(manifest, ensure_ascii=False, indent=2))
            if progress_cb:
                progress_cb('הגיבוי הושלם!', 100)
            log(f'created {scope} backup: {zip_path} ({len(included)} items)')
            return zip_path, manifest
        except Exception as e:
            log(f'create error: {e}', xbmc.LOGERROR)
            try:
                if os.path.exists(zip_path):
                    os.remove(zip_path)
            except Exception:
                pass
            return None, None

    def _add_full_userdata(self, z, progress_cb, included):
        root = C.USERDATA.rstrip('/\\')
        all_files = []
        for base, dirs, files in os.walk(root):
            rel = os.path.relpath(base, root)
            top = (rel.split(os.sep)[0] if rel != '.' else '')
            if top in FULL_EXCLUDE_DIRS:
                dirs[:] = []
                continue
            for f in files:
                if f.startswith(FULL_EXCLUDE_PREFIX) and f.endswith('.db'):
                    continue
                all_files.append(os.path.join(base, f))
        total = max(len(all_files), 1)
        for i, fp in enumerate(all_files):
            if progress_cb and i % 25 == 0:
                progress_cb(f'מגבה userdata... ({i}/{total})', int(10 + 80 * i / total))
            arc = os.path.join('userdata', os.path.relpath(fp, root)).replace(os.sep, '/')
            try:
                z.write(fp, arc)
            except Exception:
                pass
        included.append(f'userdata מלא ({total} קבצים)')

    # ---- list ----
    def list(self):
        out = []
        folder = C.backup_location()
        if not os.path.isdir(folder):
            return out
        for f in os.listdir(folder):
            if not f.endswith('.zip'):
                continue
            path = os.path.join(folder, f)
            manifest = None
            try:
                with zipfile.ZipFile(path) as z:
                    if 'manifest.json' in z.namelist():
                        manifest = json.loads(z.read('manifest.json').decode('utf-8'))
            except Exception:
                pass
            out.append({
                'filename': f,
                'path': path,
                'size': os.path.getsize(path),
                'mtime': os.path.getmtime(path),
                'manifest': manifest,
            })
        out.sort(key=lambda b: b['mtime'], reverse=True)
        return out

    # ---- restore ----
    def restore(self, zip_path, progress_cb=None):
        try:
            with zipfile.ZipFile(zip_path) as z:
                names = z.namelist()
                manifest = json.loads(z.read('manifest.json').decode('utf-8')) if 'manifest.json' in names else {}
                scope = manifest.get('scope', 'quick')
                members = [n for n in names if n != 'manifest.json']
                total = max(len(members), 1)
                for i, n in enumerate(members):
                    if progress_cb:
                        progress_cb(f'משחזר... ({i + 1}/{total})', int(10 + 80 * i / total))
                    # FULL members are under userdata/; QUICK members map to
                    # known locations under userdata.
                    rel = n[len('userdata/'):] if n.startswith('userdata/') else n
                    dest = os.path.join(C.USERDATA, rel.replace('/', os.sep))
                    os.makedirs(os.path.dirname(dest), exist_ok=True)
                    with z.open(n) as srcf, open(dest, 'wb') as dstf:
                        shutil.copyfileobj(srcf, dstf)
            if progress_cb:
                progress_cb('השחזור הושלם!', 100)
            log(f'restored {zip_path} (scope={scope})')
            return True
        except Exception as e:
            log(f'restore error: {e}', xbmc.LOGERROR)
            return False

    def delete(self, path):
        try:
            os.remove(path)
            return True
        except Exception:
            return False


# ============================================================
# UI flows (called from default.py)
# ============================================================
def _fmt(b):
    m = b.get('manifest') or {}
    scope = m.get('scope', '?')
    when = m.get('created') or datetime.fromtimestamp(b['mtime']).strftime('%Y-%m-%d %H:%M')
    mb = b['size'] / 1048576.0
    tag = 'מהיר' if scope == 'quick' else ('מלא' if scope == 'full' else scope)
    return f"[{tag}] {when}  |  {mb:.1f}MB"


def create_flow():
    dlg = xbmcgui.Dialog()
    choice = dlg.select('סוג גיבוי', [
        'גיבוי מהיר (הגדרות + מפתח Gemini + דבריד)  - מומלץ',
        'גיבוי מלא (כל userdata, ללא מטמון)',
    ])
    if choice < 0:
        return
    scope = 'quick' if choice == 0 else 'full'
    progress = xbmcgui.DialogProgress()
    progress.create(ADDON_NAME, 'מתחיל גיבוי...')
    path, manifest = BackupManager().create(scope, lambda m, p: progress.update(p, m))
    progress.close()
    if path:
        items = "\n".join(f"- {x}" for x in (manifest.get('items') or []))
        dlg.ok(ADDON_NAME, f"[COLOR {SUCCESS}]הגיבוי נוצר![/COLOR]\n\n{items}\n\n{os.path.basename(path)}")
    else:
        dlg.ok(ADDON_NAME, f"[COLOR {ERROR}]הגיבוי נכשל![/COLOR]")


def restore_flow():
    dlg = xbmcgui.Dialog()
    mgr = BackupManager()
    backups = mgr.list()
    if not backups:
        dlg.ok(ADDON_NAME, 'לא נמצאו גיבויים.')
        return
    sel = dlg.select('בחר גיבוי לשחזור', [_fmt(b) for b in backups])
    if sel < 0:
        return
    chosen = backups[sel]
    if not dlg.yesno(ADDON_NAME,
                     f"לשחזר את הגיבוי הזה?\n\n{_fmt(chosen)}\n\n"
                     f"[COLOR {WARN}]ההגדרות הנוכחיות יוחלפו.[/COLOR]",
                     yeslabel='שחזר', nolabel='ביטול'):
        return
    progress = xbmcgui.DialogProgress()
    progress.create(ADDON_NAME, 'משחזר...')
    ok = mgr.restore(chosen['path'], lambda m, p: progress.update(p, m))
    progress.close()
    if ok:
        if dlg.yesno(ADDON_NAME,
                     f"[COLOR {SUCCESS}]השחזור הושלם![/COLOR]\n\nיש להפעיל מחדש את Kodi כדי להחיל. להפעיל עכשיו?",
                     yeslabel='הפעל מחדש', nolabel='מאוחר יותר'):
            xbmc.executebuiltin('Quit')
    else:
        dlg.ok(ADDON_NAME, f"[COLOR {ERROR}]השחזור נכשל![/COLOR]")


def manage_flow():
    dlg = xbmcgui.Dialog()
    mgr = BackupManager()
    backups = mgr.list()
    if not backups:
        dlg.ok(ADDON_NAME, 'לא נמצאו גיבויים.')
        return
    idx = dlg.multiselect('בחר גיבויים למחיקה', [_fmt(b) for b in backups])
    if not idx:
        return
    if not dlg.yesno(ADDON_NAME, f"למחוק {len(idx)} גיבויים?"):
        return
    n = sum(1 for i in idx if mgr.delete(backups[i]['path']))
    dlg.ok(ADDON_NAME, f"[COLOR {SUCCESS}]נמחקו {n} גיבויים.[/COLOR]")
